name = "erdos516_fejer_lean4web"
version = "0.1.0"
defaultTargets = ["Erdos516FejerLean4Web"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.35.0-rc2"

[[lean_lib]]
name = "Erdos516FejerLean4Web"
